### ISSUE TITLE
Conversion fails, if the database does not contain all the necessary fields

### ISSUE THREAD

**Issue by arpsoid** [rdiaz02/Zotero-to-Referey#8]
That's an issue with the `ZtoDocuments` function around line 92. The dataframe created is oblidged to contain all the fields such as `Z$edition, Z$institution, Z$numPages`. However, if the zotero database does not contain the items, that have those fields, then the `dcast` operation at line 278 will return a dataframe without those columns, and `ZtoDocuments` will return error.
To fix that, a check is needed, e.g. using the `names()` function.
This issue is not a problem, when the database is relatively big, and all types of records are present.

**Comment by rdiaz02** [comment]
Could you submit a pull request? I'll be glad to incorporate it.

**Comment by arpsoid** [comment]
Done, thank you, please kindly check if I am correct.

**Comment by rdiaz02** [comment]
It does, as far as I can tell. Thanks a lot (and apologies for the delay).
